### ISSUE TITLE
Module `antigravity` has an implementation of geohashing

### ISSUE THREAD

**Issue by anqur** [OrkoHunter/python-easter-eggs#2]
- That is the algorithm from an xkcd comic [Geohashing](https://xkcd.com/426/), maybe it is good to mention that
    + FYI: http://wiki.xkcd.com/geohashing/Implementations#Python_3_standard_library

**Comment by OrkoHunter** [comment]
Cool! Would you like to make the changes and create a PR?

**Comment by anqur** [comment]
Sure! Just started making this!
